//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransferWorkflow.BankBSvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BankBSvc.IBankBService")]
    public interface IBankBService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankBService/Deposit", ReplyAction="http://tempuri.org/IBankBService/DepositResponse")]
        TransferWorkflow.BankBSvc.DepositResponse Deposit(TransferWorkflow.BankBSvc.DepositRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankBService/Deposit", ReplyAction="http://tempuri.org/IBankBService/DepositResponse")]
        System.Threading.Tasks.Task<TransferWorkflow.BankBSvc.DepositResponse> DepositAsync(TransferWorkflow.BankBSvc.DepositRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Deposit", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DepositRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public double amount;
        
        public DepositRequest() {
        }
        
        public DepositRequest(double amount) {
            this.amount = amount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DepositResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DepositResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public double DepositResult;
        
        public DepositResponse() {
        }
        
        public DepositResponse(double DepositResult) {
            this.DepositResult = DepositResult;
        }
    }
}
