//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransferWorkflow.BankASvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BankASvc.IBankAService")]
    public interface IBankAService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankAService/Withdraw", ReplyAction="http://tempuri.org/IBankAService/WithdrawResponse")]
        TransferWorkflow.BankASvc.WithdrawResponse Withdraw(TransferWorkflow.BankASvc.WithdrawRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankAService/Withdraw", ReplyAction="http://tempuri.org/IBankAService/WithdrawResponse")]
        System.Threading.Tasks.Task<TransferWorkflow.BankASvc.WithdrawResponse> WithdrawAsync(TransferWorkflow.BankASvc.WithdrawRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Withdraw", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class WithdrawRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public double amount;
        
        public WithdrawRequest() {
        }
        
        public WithdrawRequest(double amount) {
            this.amount = amount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WithdrawResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class WithdrawResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public double WithdrawResult;
        
        public WithdrawResponse() {
        }
        
        public WithdrawResponse(double WithdrawResult) {
            this.WithdrawResult = WithdrawResult;
        }
    }
}
