//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientNet4.FirstWcfSvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FirstWcfSvc.IFirstWcfService")]
    public interface IFirstWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirstWcfService/NumToEng", ReplyAction="http://tempuri.org/IFirstWcfService/NumToEngResponse")]
        string NumToEng(int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirstWcfService/Add200", ReplyAction="http://tempuri.org/IFirstWcfService/Add200Response")]
        string Add200(int number);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFirstWcfServiceChannel : ClientNet4.FirstWcfSvc.IFirstWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FirstWcfServiceClient : System.ServiceModel.ClientBase<ClientNet4.FirstWcfSvc.IFirstWcfService>, ClientNet4.FirstWcfSvc.IFirstWcfService {
        
        public FirstWcfServiceClient() {
        }
        
        public FirstWcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FirstWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FirstWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FirstWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string NumToEng(int number) {
            return base.Channel.NumToEng(number);
        }
        
        public string Add200(int number) {
            return base.Channel.Add200(number);
        }
    }
}
